spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: anymind
      uri: mongodb://localhost:27017
  jpa:
    show-sql: true


server:
  servlet:
    context-path: /anymind